# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtvFzHjHItMJRlQj0VuYIytpV9wofdoO
"""

import datetime
def chatbot():
    print("Chatbot: Hello! Type 'bye' to exit.")

    # Loop runs continuously
    while True:
        user_input = input("You: ").lower()

        # Exit condition
        if user_input == "bye":
            print("Chatbot: Goodbye!")
            break

        # Greeting condition
        elif "hi" in user_input or "hello" in user_input:
            print("Chatbot: Hello! How can I help you?")

        # Asking chatbot name
        elif "name" in user_input:
            print("Chatbot: I am a simple rule-based chatbot.")

        # Time feature

        elif "time" in user_input:
            current_time = datetime.datetime.now().strftime("%H:%M:%S")
            print("Chatbot: Current time is", current_time)

        # Help option
        elif "help" in user_input:
            print("Chatbot: You can ask me about greetings, name, or time.")

        # Default response
        else:
            print("Chatbot: Sorry, I didn't understand that.")

# Run chatbot
chatbot()
